version: '3.9'
services:
  ui:
    container_name: ui
    build:
      dockerfile: Dockerfile
      context: ./ui
    ports:
      - 3000:3000
    links:
      - api
  api:
    container_name: api
    build:
      dockerfile: Dockerfile
      context: ./api
    ports:
      - 4080:4080
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_TYPE=${DB_TYPE}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB=${PG_DB}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
volumes:
  pgdata: {}
